lprnet:
    onnx_file:      "./models/LPR/recognize/lprnet.onnx"
    engine_file:    "./models/LPR/recognize/lprnet.trtmodel"
    labels_file:    "京沪津渝冀晋蒙辽吉黑苏浙皖闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新0123456789ABCDEFGHJKLMNPQRSTUVWXYZIO-"
    maxBatchSize:   5
    input_Dim:      [[1,3,24,94],[1,3,24,94],[100,3,24,94]]
    mean:           [ 1., 1., 1. ]
    std:            [ 1., 1., 1. ]
    scale:          0.0078125
