retinalp:
    onnx_file:      "./models/LPR/detect/retinaLP.onnx"
    engine_file:    "./models/LPR/detect/retinaLP.trtmodel"
    maxBatchSize:   10
    input_Dim:      [[1,3,1280,1280],[5,3,1280,1280],[10,3,1280,1280]]
    strides:        [8,16,32]
    anchors:        [[24,48],[96,192],[384,768]]
    obj_threshold:  0.5
    nms_threshold:  0.6
    max_objs:       1000
    num_classes:    1
    mean:           [104,117,123]
    std:            [1.,1.,1.]
    scale:          1.
