ghostnet:
    onnx_file:      "./models/classify/ghostnet/ghostnet.onnx"
    engine_file:    "./models/classify/ghostnet/ghostnet.trtmodel"
    labels_file:    "./configs/classify/label.name"
    maxBatchSize:   5
    input_Dim:      [[1,3,224,224]]
    mean:           [ 0.485, 0.456, 0.406 ]
    std:            [ 0.229, 0.224, 0.225 ]
    scale:          0.003921568627451
