face:
    detect:         "./configs/face/retinaface.yaml"
    landmark:       "./configs/face/landmark.yaml"
    gender_age:     "./configs/face/gender_age.yaml"
    recognize:      "./configs/face/arcface.yaml"
    db_path:        "./results/"