retinaface:
    onnx_file:      "./models/retinaface/mobilenet0.25_Final.onnx"
    engine_file:    "./models/retinaface/mobilenet0.25_Final.trtmodel"
    labels_file:    "./configs/face.names"
    maxBatchSize:   5
    input_Dim:      [[1,3,640,640],[1,3,640,640],[5,3,640,640]]
    strides:        [8,16,32]
    anchors:        [[16,32],[64,128],[256,512]]
    obj_threshold:  0.5
    nms_threshold:  0.6
    max_objs:       1000
    num_classes:    1
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          1.
