yolov5s:
    onnx_file:      "./models/yolo/yolov3-tiny.onnx"
    engine_file:    "./models/yolo/yolov3-tiny.trtmodel"
    labels_file:    "./configs/coco.names"
    maxBatchSize:   5
    input_Dim:      [[1,3,640,640],[1,3,640,640],[5,3,640,640]]
    strides:        [16, 32]
    num_anchors:    [3,  3]
    anchors:        [[[10.,14.], [23.,27.], [37.,58.]], [[81.,82.], [135.,169.], [344.,319.]]]
    obj_threshold:  0.4
    nms_threshold:  0.6
    max_objs:       100
    num_classes:    80
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
