yolov5s:
    onnx_file:      "./models/yolo/yolov4-p5.onnx"
    engine_file:    "./models/yolo/yolov4-p5.trtmodel"
    labels_file:    "./configs/coco.names"
    maxBatchSize:   5
    input_Dim:      [[1,3,896,896],[1,3,896,896],[5,3,896,896]]
    strides:        [8, 16, 32]
    num_anchors:    [4,  4,  4]
    anchors:        [[[13.,17.], [31.,25.], [24.,51.], [61.,45.]], [[48.,102.], [119.,96.], [97.,189.], [217.,184.]], [[171.,384.],[324.,451.],[616.,618.],[800.,800.]]]
    obj_threshold:  0.4
    nms_threshold:  0.6
    max_objs:       100
    num_classes:    80
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          0.0039216
