dbface:
    onnx_file:      "./models/face/dbface/dbface-b1.onnx"
    engine_file:    "./models/face/dbface/dbface-b1.trtmodel"
    maxBatchSize:   5
    input_Dim:      [[1,3,640,640]]
    strides:        4
    obj_threshold:  0.5
    nms_threshold:  0.6
    max_objs:       1000
    num_classes:    1
    mean:           [0.408, 0.447, 0.47]
    std:            [0.289, 0.274, 0.278]
    scale:          0.003921568627451
