face_alignment:
    onnx_file:      "./models/face/alignment/2d106det-d.onnx"
    engine_file:    "./models/face/alignment/2d106det-d.trtmodel"
    maxBatchSize:   5
    input_Dim:      [[1,3,192,192],[1,3,192,192],[1,3,192,192]]
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          1.
