gender_age:
    onnx_file:      "./models/face/gender-age/gender-age-d.onnx"
    engine_file:    "./models/face/gender-age/gender-age-d.trtmodel"
    maxBatchSize:   100
    input_Dim:      [[1,3,112,112],[1,3,112,112],[100,3,112,112]]
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          1.
