gender_age:
    onnx_file:      "./models/face/gender-age/gender-age.onnx"
    engine_file:    "./models/face/gender-age/gender-age.trtmodel"
    maxBatchSize:   5
    input_Dim:      [[1,3,112,112],[1,3,112,112],[1,3,112,112]]
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          1.
