dmcount:
    onnx_file:      "./models/crowdcount/dm_count.onnx"
    engine_file:    "./models/crowdcount/dm_count.trtmodel"
    maxBatchSize:   5
    input_Dim:      [[1,3,1280,1280],[3,3,1280,1280],[5,3,1280,1280]]
    mean:           [ 0, 0, 0 ]
    std:            [ 1, 1, 1 ]
    scale:          0.00390625
