nanodet:
    onnx_file:      "./models/detect/nanodet/nanodet_g-simplify.onnx"
    engine_file:    "./models/detect/nanodet/nanodet_g-simplify.trtmodel"
    labels_file:    "./configs/detect/coco.names"
    maxBatchSize:   1
    input_Dim:      [[1,3,416,416],[1,3,416,416],[1,3,416,416]]
    strides:        [8, 16, 32]
    reg_max:        10
    obj_threshold:  0.4
    nms_threshold:  0.6
    max_objs:       100
    num_classes:    80
    mean:           [103.53, 116.28, 123.675]
    std:            [57.375, 57.12, 58.395]
    scale:          1.
