yolov5s:
    onnx_file:      "./models/detect/yolo/yolov4-p7.onnx"
    engine_file:    "./models/detect/yolo/yolov4-p7.trtmodel"
    labels_file:    "./configs/detect/coco.names"
    maxBatchSize:   5
    input_Dim:      [[1,3,1536,1536],[1,3,1536,1536],[5,3,1536,1536]]  
    strides:        [8, 16, 32, 64, 128]
    num_anchors:    [4, 4, 4, 4, 4]
    anchors:        [[[13.,17.], [22.,25.], [27.,66.], [55.,41.]], [[57.,88.], [112.,69.], [69.,177.], [136.,132.]], [[136.,138.],[287.,114.],[134.,275.],[268.,248.]],[[268.,248.],[232.,504.],[445.,416.],[640.,640.]],[[812.,393.],[477.,808.],[1070.,908.],[1408.,1408.]]]
    obj_threshold:  0.4
    nms_threshold:  0.6
    max_objs:       100
    num_classes:    80
    mean:           [0.,0.,0.]
    std:            [1.,1.,1.]
    scale:          0.0039216
